$(document).ready(function(){simpleCart=new Cart($.currencyCode+'_cart');simpleCart.currency=$.currencyCode;simpleCart.currencySymbol=function(){return $.currencyUnit;};simpleCart.checkoutTo='custom';simpleCart.cartHeaders=['Name','Quantity','increment_noHeader','decrement_noHeader','Total','Remove'];simpleCart.customCheckout=function(){gotoNextPage("/checkout")}
simpleCart.onAddItem=function(name,quantity,price){$.jGrowl(name,{theme:'registria',header:$.translator.t('Added to cart'),life:10000});}
simpleCart.onRejectAdd=function(name,quantity,limit){$.jGrowl("You may only add "+limit+" of "+name,{theme:'registria-error',header:$.translator.t('Error'),sticky:true});}
simpleCart.onRejectAddSupport=function(name,quantity,maxDuration,itemDuration){$.jGrowl("Unable to extend warranty past "+Math.floor(maxDuration/365)+" years",{theme:'registria-error',header:$.translator.t('Error'),sticky:true});}
$.each(['Name','Quantity','Total','Remove'],function(){$("div.cartHeaders > div.item<%= header %>").html($.translator.t(this));});$("div.itemRemove > a").html($.translator.t('Remove'));$("#registria_checkout").click(function(e){if(simpleCart.quantity<1)
alert($.translator.t('Your Cart is empty'));else
gotoNextPage("/checkout");});});var NextId=1,Custom="Custom",GoogleCheckout="GoogleCheckout",PayPal="PayPal",Email="Email",AustralianDollar=AUD="AUD",CanadianDollar=CAD="CAD",CzechKoruna=CZK="CZK",DanishKrone=DKK="DKK",Euro=EUR="EUR",HongKongDollar=HKD="HKD",HungarianForint=HUF="HUF",IsraeliNewSheqel=ILS="ILS",JapaneseYen=JPY="JPY",MexicanPeso=MXN="MXN",NorwegianKrone=NOK="NOK",NewZealandDollar=NZD="NZD",PolishZloty=PLN="PLN",PoundSterling=GBP="GBP",SingaporeDollar=SGD="SGD",SwedishKrona=SEK="SEK",SwissFranc=CHF="CHF",USDollar=USD="USD";function Cart(name){var me=this;me.Version='2.0.1';me.Shelf=new Shelf();me.items={};me.isLoaded=false;me.pageIsReady=false;me.quantity=0;me.total=0;me.totals={};me.taxRate=0;me.taxCost=0;me.discountAmount=0;me.shippingFlatRate=0;me.shippingTotalRate=0;me.shippingQuantityRate=0;me.shippingRate=0;me.shippingCost=0;me.currency=USD;me.checkoutTo=PayPal;me.email="";me.merchantId="";me.cartHeaders=['Name','Price','Quantity','Total'];me.onUpdate=null;me.onAddItem=null;me.onRejectAdd=null;me.onRejectAddSupport=null;me.onItemIncrement=null;me.onItemDecrement=null;me.onItemRemove=null;me.products={};if(name==null)
me.name='simpleCart';else
me.name=name;me.getTotal=function(currencyCode){me.update();return me.totals[currencyCode.toUpperCase()];};me.validForCurrency=function(currencyCode){for(var item_i in me.items){var item=me.items[item_i];if(!item.product.hasCurrency(currencyCode)){return false;}}
return true;};me.getInvalidItemsForCurrency=function(currencyCode){var invalidItems=[];for(var item_i in me.items){var item=me.items[item_i];if(!item.product.hasCurrency(currencyCode)){invalidItems.push(item);}}
return invalidItems;};me.getInvalidProductsForCurrency=function(currencyCode){var invalidItems=me.getInvalidItemsForCurrency(currencyCode);var invalidProducts=[];for(var item_i in invalidItems){var item=invalidItems[item_i];invalidProducts.push(item.product);}
return invalidProducts;};me.removeInvalidItemsForCurrency=function(currencyCode){var invalidItems=me.getInvalidItemsForCurrency(currencyCode);for(var item_i in invalidItems){var item=invalidItems[item_i];item.remove();}};me.containsItemsForCurrency=function(currencyCode){for(var item_i in me.items){var item=me.items[item_i];if(item.product.hasCurrency(currencyCode)){return true;}}
return false;};me.initializeProducts=function(arr){for(var i in arr){var prod=arr[i];var p=new ProductInfo();p.id=prod.id;p.name=prod.n;p.maxDuration=prod.mD;p.maxQuantity=prod.mQ;for(var pl_i in prod.p){var pl=prod.p[pl_i];var currency={code:pl.c.toUpperCase(),incrementalPricing:pl.i,pricing:[]};for(var price_i in pl.p){var price=pl.p[price_i];currency.pricing.push({max:price.m,price:price.p,discountPrice:price.dP});};if(currency.pricing.length>0){p.addCurrency(currency);if(pl.s){p.setDefaultCurrency(currency);}};};for(var x in prod.s){var method=prod.s[x];s={id:method.id,name:method.n,pricing:[]};for(var j in method.p){var price=method.p[j];s.pricing.push({max:price.m,shipping:price.s,handling:price.h})}
p.addShippingMethod(s);}
me.products[p.id]=p;}}
me.setDiscountAmount=function(amount){var me=this;me.discountAmount=parseFloat(amount);me.update();};me.add=function(){var me=this;if(!me.pageIsReady){me.initializeView();me.update();}
if(!me.isLoaded){me.load();me.update();}
var newItem=new CartItem();if(!arguments||arguments.length===0){error('No values passed for item.');return;}
var argumentArray=arguments;if(arguments[0]&&typeof(arguments[0])!='string'&&typeof(arguments[0])!='number'){argumentArray=arguments[0];}
newItem.parseValuesFromArray(argumentArray);newItem.checkQuantityAndPrice();if(newItem.checkDuration()&&newItem.checkQuantity()){if(me.hasItem(newItem)){var id=me.hasItem(newItem);var newQuantity=parseInt(me.items[id].quantity,10)+parseInt(newItem.quantity,10);me.items[id].quantity=newQuantity;if(newQuantity>=me.items[id].quantity){if($.isFunction(me.onItemIncrement)){me.onItemIncrement(me.items[id]);}}
else
{if($.isFunction(me.onItemDecrement)){me.onItemDecrement(me.items[id]);}}}else{me.items[newItem.id]=newItem;}
if($.isFunction(me.onAddItem)){me.onAddItem(newItem.name,newItem.quantity,newItem.price);}
me.update();}};me.remove=function(id){var tempArray={};for(var item in this.items){if(item!=id){tempArray[item]=this.items[item];}}
this.items=tempArray;};me.empty=function(){simpleCart.items={};simpleCart.discountAmount=0.0;simpleCart.update();};me.find=function(criteria){if(!criteria)
return null;var results=[];for(var next in me.items){var item=me.items[next],fits=true;for(var name in criteria){if(!item[name]||item[name]!=criteria[name])
fits=false;}
if(fits)
results.push(me.next)}
return(results.length==0)?null:results;}
me.checkout=function(){if(simpleCart.quantity===0){error("Cart is empty");return;}
switch(simpleCart.checkoutTo){case PayPal:simpleCart.paypalCheckout();break;case GoogleCheckout:simpleCart.googleCheckout();break;case Email:simpleCart.emailCheckout();break;default:simpleCart.customCheckout();break;}};me.paypalCheckout=function(){var me=this,winpar="scrollbars,location,resizable,status",strn="https://www.paypal.com/cgi-bin/webscr?cmd=_cart"+"&upload=1"+"&business="+me.email+"&currency_code="+me.currency,counter=1,itemsString="";if(me.taxRate){strn=strn+"&tax_cart="+me.currencyStringForPaypalCheckout(me.taxCost);}
for(var current in me.items){var item=me.items[current];var optionsString="";for(var field in item){if(typeof(item[field])!="function"&&field!="id"&&field!="price"&&field!="quantity"&&field!="name"&&field!="shipping"){optionsString=optionsString+", "+field+"="+item[field];}}
optionsString=optionsString.substring(2);itemsString=itemsString+"&item_name_"+counter+"="+item.name+"&item_number_"+counter+"="+counter+"&quantity_"+counter+"="+item.quantity+"&amount_"+counter+"="+me.currencyStringForPaypalCheckout(item.price)+"&on0_"+counter+"="+"Options"+"&os0_"+counter+"="+optionsString;counter++;}
if(me.shipping()!=0){itemsString=itemsString+"&item_name_"+counter+"=Shipping"+"&item_number_"+counter+"="+counter+"&quantity_"+counter+"=1"+"&amount_"+counter+"="+me.currencyStringForPaypalCheckout(me.shippingCost);}
strn=strn+itemsString;window.open(strn,"paypal",winpar);};me.googleCheckout=function(){var me=this;if(me.currency!=USD&&me.currency!=GBP){error("Google Checkout only allows the USD and GBP for currency.");return;}else if(me.merchantId===""||me.merchantId===null||!me.merchantId){error("No merchant Id for google checkout supplied.");return;}
var form=document.createElement("form"),counter=1;form.style.display="none";form.method="POST";form.action="https://checkout.google.com/api/checkout/v2/checkoutForm/Merchant/"+
me.merchantId;form.acceptCharset="utf-8";for(var current in me.items){var item=me.items[current];form.appendChild(me.createHiddenElement("item_name_"+counter,item.name));form.appendChild(me.createHiddenElement("item_quantity_"+counter,item.quantity));form.appendChild(me.createHiddenElement("item_price_"+counter,item.price));form.appendChild(me.createHiddenElement("item_currency_"+counter,me.currency));form.appendChild(me.createHiddenElement("item_tax_rate_"+counter,me.taxRate));form.appendChild(me.createHiddenElement("_charset_",""));var descriptionString="";for(var field in item){if(typeof(item[field])!="function"&&field!="id"&&field!="quantity"&&field!="price")
{descriptionString=descriptionString+", "+field+": "+item[field];}}
descriptionString=descriptionString.substring(1);form.appendChild(me.createHiddenElement("item_description_"+counter,descriptionString));counter++;}
document.body.appendChild(form);form.submit();document.body.removeChild(form);};me.emailCheckout=function(){return;};me.customCheckout=function(){return;};me.load=function(){var me=this;me.items={};me.total=0.00;me.quantity=0;me.discountAmount=0.00;if(readCookie(me.name)){var main=unescape(readCookie(me.name)).split('>>');if(main[1]!==undefined)
me.discountAmount=parseFloat(main[1]);if(main[0]!=""){var data=main[0].split('++');for(var x=0,xlen=data.length;x<xlen;x++){var info=data[x].split('||');var newItem=new CartItem();if(newItem.parseValuesFromArray(info)){newItem.checkQuantityAndPrice();me.items[newItem.id]=newItem;}}}}
me.isLoaded=true;};me.save=function(){var dataString="";for(var item in this.items){dataString=dataString+"++"+this.items[item].print();}
dataString=dataString.substring(2);dataString+=">>";dataString+=this.discountAmount.toString();createCookie(me.name,dataString,30);};me.initializeView=function(){var me=this;me.totalOutlets=getElementsByClassName('simpleCart_total');me.quantityOutlets=getElementsByClassName('simpleCart_quantity');me.cartDivs=getElementsByClassName('simpleCart_items');me.taxCostOutlets=getElementsByClassName('simpleCart_taxCost');me.taxRateOutlets=getElementsByClassName('simpleCart_taxRate');me.shippingCostOutlets=getElementsByClassName('simpleCart_shippingCost');me.finalTotalOutlets=getElementsByClassName('simpleCart_finalTotal');me.addEventToArray(getElementsByClassName('simpleCart_checkout'),simpleCart.checkout,"click");me.addEventToArray(getElementsByClassName('simpleCart_empty'),simpleCart.empty,"click");me.Shelf.readPage();me.pageIsReady=true;};me.updateView=function(){me.updateViewTotals();if(me.cartDivs&&me.cartDivs.length>0){me.updateCartView();}};me.updateViewTotals=function(){var outlets=[["quantity","none"],["total","currency"],["shippingCost","currency"],["taxCost","currency"],["taxRate","percentage"],["finalTotal","currency"]];for(var x=0,xlen=outlets.length;x<xlen;x++){var arrayName=outlets[x][0]+"Outlets",outputString;for(var element in me[arrayName]){switch(outlets[x][1]){case"none":outputString=""+me[outlets[x][0]];break;case"currency":outputString=me.valueToCurrencyString(me[outlets[x][0]]);break;case"percentage":outputString=me.valueToPercentageString(me[outlets[x][0]]);break;default:outputString=""+me[outlets[x][0]];break;}
me[arrayName][element].innerHTML=""+outputString;}}};me.updateCartView=function(){var newRows=[],x,newRow,item,current,header,newCell,info,outputValue,option,headerInfo;newRow=document.createElement('div');for(header in me.cartHeaders){newCell=document.createElement('div');headerInfo=me.cartHeaders[header].split("_");newCell.innerHTML=headerInfo[0];newCell.className="item"+headerInfo[0];for(x=1,xlen=headerInfo.length;x<xlen;x++){if(headerInfo[x].toLowerCase()=="noheader"){newCell.style.display="none";}}
newRow.appendChild(newCell);}
newRow.className="cartHeaders";newRows[0]=newRow;x=1;if($.objectSize(simpleCart.items)==0){newRow=document.createElement('div');newRow.innerHTML="Your cart is empty";newRow.className="itemContainer empty";newRows[x]=newRow;}
else{for(current in me.items){newRow=document.createElement('div');item=me.items[current];var q=parseInt(item.quantity,10);for(header in me.cartHeaders){newCell=document.createElement('div');info=me.cartHeaders[header].split("_");switch(info[0].toLowerCase()){case"total":outputValue=me.valueToCurrencyString(item.getTotal());break;case"increment":if(item.quantitycontrols)
outputValue=me.valueToLink("+","javascript:;","onclick=\"simpleCart.items[\'"+item.id+"\'].increment();\"");else
outputValue="";break;case"decrement":if(item.quantitycontrols)
outputValue=me.valueToLink("-","javascript:;","onclick=\"simpleCart.items[\'"+item.id+"\'].decrement();\"");else
outputValue="";break;case"remove":outputValue=me.valueToLink("Remove","javascript:;","onclick=\"simpleCart.items[\'"+item.id+"\'].remove();\"");break;case"price":outputValue=me.valueToCurrencyString(item[info[0].toLowerCase()]?item[info[0].toLowerCase()]:" ");break;default:outputValue=item[info[0].toLowerCase()]?item[info[0].toLowerCase()]:" ";break;}
for(var y=1,ylen=info.length;y<ylen;y++){option=info[y].toLowerCase();switch(option){case"image":case"img":outputValue=me.valueToImageString(outputValue);break;case"input":outputValue=me.valueToTextInput(outputValue,"onchange=\"simpleCart.items[\'"+item.id+"\'].set(\'"+outputValue+"\' , this.value);\"");break;case"div":case"span":case"h1":case"h2":case"h3":case"h4":case"p":outputValue=me.valueToElement(option,outputValue,"");break;case"noheader":break;default:error("unkown header option: "+option);break;}}
newCell.innerHTML=outputValue;newCell.className="item"+info[0];newRow.appendChild(newCell);}
newRow.className="itemContainer";newRows[x]=newRow;x++;}}
for(current in me.cartDivs){var div=me.cartDivs[current];while(div.childNodes[0]){div.removeChild(div.childNodes[0]);}
for(var j=0,jLen=newRows.length;j<jLen;j++){div.appendChild(newRows[j]);}}};me.addEventToArray=function(array,functionCall,theEvent){for(var outlet in array){var element=array[outlet];if(element.addEventListener){element.addEventListener(theEvent,functionCall,false);}else if(element.attachEvent){element.attachEvent("on"+theEvent,functionCall);}}};me.createHiddenElement=function(name,value){var element=document.createElement("input");element.type="hidden";element.name=name;element.value=value;return element;};me.currencySymbol=function(){switch(me.currency){case JPY:return"&yen;";case EUR:return"&euro;";case GBP:return"&pound;";case USD:case CAD:case AUD:case NZD:case HKD:case SGD:return"&#36;";default:return"";}};me.currencyDecimal=function(){switch(me.currency){case CAD:return",";case EUR:return",";default:return".";}};me.currencySymbolAfter=function(){switch(me.currency){case CAD:return true;default:return false;}};me.currencyStringForPaypalCheckout=function(value){if(me.currencySymbol()=="&#36;"){return"$"+parseFloat(value).toFixed(2);}else{return""+parseFloat(value).toFixed(2);}};me.valueToCurrencyString=function(value,scale){scale=(scale==undefined?2:scale)
return parseFloat(value).toCurrency(me.currencySymbol(),me.currencyDecimal(),me.currencySymbolAfter(),scale);};me.valueToPercentageString=function(value){return parseFloat(100*value)+"%";};me.valueToImageString=function(value){if(value.match(/<\s*img.*src\=/)){return value;}else{return"<img src=\""+value+"\" />";}};me.valueToTextInput=function(value,html){return"<input type=\"text\" value=\""+value+"\" "+html+" />";};me.valueToLink=function(value,link,html){return"<a href=\""+link+"\" "+html+" >"+value+"</a>";};me.valueToElement=function(type,value,html){return"<"+type+" "+html+" > "+value+"</"+type+">";};me.hasItem=function(item){for(var current in me.items){var testItem=me.items[current];var matches=true;for(var field in item){if(typeof(item[field])!="function"&&field!="quantity"&&field!="id"){if(item[field]!=testItem[field]){matches=false;}}}
if(matches){return current;}}
return false;};me.getTotalSupportDuration=function(cartItem){var duration=0;for(var current in me.items){var testItem=me.items[current];if(testItem.registration_id==cartItem.registration_id){duration+=(parseInt(testItem.quantity,10)*parseInt(testItem.product_support_duration,10));}}
return duration;};me.update=function(){if(!simpleCart.isLoaded){simpleCart.load();}
if(!simpleCart.pageIsReady){simpleCart.initializeView();}
me.updateTotals();me.updateView();me.save();if($.isFunction(me.onUpdate)){me.onUpdate();}};me.updateTotals=function(){me.total=0;me.quantity=0;me.totals={};for(var current in me.items){var item=me.items[current];var p=item.product;if(item.quantity<1){item.remove();}else if(item.quantity!==null&&item.quantity!="undefined"){me.quantity=parseInt(me.quantity,10)+parseInt(item.quantity,10);}
me.total=parseFloat(me.total)+parseFloat(item.getTotal());if(p!==undefined){for(var c_i in p.currencies){var pCurrency=p.currencies[c_i];if(me.totals[pCurrency.code]===undefined)
me.totals[pCurrency.code]=0;me.totals[pCurrency.code]=parseFloat(me.totals[pCurrency.code])+parseFloat(item.getTotal(pCurrency.code));}}}
me.total-=parseFloat(me.discountAmount);me.shippingCost=me.shipping();me.taxCost=parseFloat(me.total)*me.taxRate;me.finalTotal=me.shippingCost+me.taxCost+me.total;};me.shipping=function(){if(parseInt(me.quantity,10)===0)
return 0;var shipping=parseFloat(me.shippingFlatRate)+
parseFloat(me.shippingTotalRate)*parseFloat(me.total)+
parseFloat(me.shippingQuantityRate)*parseInt(me.quantity,10),nextItem,next;for(next in me.items){nextItem=me.items[next];if(nextItem.shipping){if(typeof nextItem.shipping=='function'){shipping+=parseFloat(nextItem.shipping());}else{shipping+=parseFloat(nextItem.shipping);}}}
return shipping;}
me.initialize=function(){simpleCart.initializeView();simpleCart.load();simpleCart.update();};}
function CartItem(){this.id="c"+NextId++;this.quantitycontrols=true;this.product;}
CartItem.prototype.set=function(field,value){field=field.toLowerCase();if(typeof(this[field])!="function"&&field!="id"){if(field=="quantity"){value=value.replace(/[^(\d|\.)]*/gi,"");value=value.replace(/,*/gi,"");value=parseInt(value,10);}else if(field=="price"){value=value.replace(/[^(\d|\.)]*/gi,"");value=value.replace(/,*/gi,"");value=parseFloat(value);}else if(field=="product_id"){this.product=simpleCart.products[value];}
if(typeof(value)=="number"&&isNaN(value)){error("Improperly formatted input.");}else{this[field]=value;this.checkQuantityAndPrice();}}else{error("Cannot change "+field+", this is a reserved field.");}
simpleCart.update();};CartItem.prototype.increment=function(){this.quantity=parseInt(this.quantity,10)+1;if(this.checkQuantity()){if($.isFunction(simpleCart.onItemIncrement)){simpleCart.onItemIncrement(this);}
simpleCart.update();}
else
this.quantity=parseInt(this.quantity,10)-1;};CartItem.prototype.decrement=function(){if(parseInt(this.quantity,10)<2){this.remove();}else{this.quantity=parseInt(this.quantity,10)-1;if(this.checkQuantity()){if($.isFunction(simpleCart.onItemDecrement)){simpleCart.onItemDecrement(this);}
simpleCart.update();}
else
this.quantity=parseInt(this.quantity,10)+1;}};CartItem.prototype.print=function(){var returnString='';for(var field in this){if(typeof(this[field])!="function"){returnString+=escape(field)+"="+escape(this[field])+"||";}}
return returnString.substring(0,returnString.length-2);};CartItem.prototype.checkQuantityAndPrice=function(){if(!this.price||this.quantity==null||this.quantity=='undefined'){this.quantity=1;error('No quantity for item.');}else{this.quantity=(""+this.quantity).replace(/,*/gi,"");this.quantity=parseInt((""+this.quantity).replace(/[^(\d|\.)]*/gi,""),10);if(isNaN(this.quantity)){error('Quantity is not a number.');this.quantity=1;}}
if(!this.price||this.price==null||this.price=='undefined'){this.price=0.00;error('No price for item or price not properly formatted.');}else{this.price=(""+this.price).replace(/,*/gi,"");this.price=parseFloat((""+this.price).replace(/[^(\d|\.)]*/gi,""));if(isNaN(this.price)){error('Price is not a number.');this.price=0.00;}}};CartItem.prototype.checkDuration=function(){try{if(this.registration_id!=null&&this.registration_id!=""){var maxDuration=parseInt(simpleCart.products[this.registered_product_id].maxDuration,10);var thisDuration=parseInt(this.quantity,10)*parseInt(this.product_support_duration,10);var cartDuration=simpleCart.getTotalSupportDuration(this);var wouldBeDuration=parseInt(this.current_support_duration,10)+thisDuration+cartDuration;if(wouldBeDuration>maxDuration)
{if($.isFunction(simpleCart.onRejectAddSupport))
simpleCart.onRejectAddSupport(this.name,this.quantity,maxDuration,thisDuration);return false;}}}catch(err){error(err)}
return true;};CartItem.prototype.checkQuantity=function(){try{var newQuantity=parseInt(this.quantity,10);if(simpleCart.hasItem(this)){var id=simpleCart.hasItem(this);if(!(this===simpleCart.items[id]))
newQuantity+=parseInt(simpleCart.items[id].quantity,10);}
var maxQuantity=parseInt(this.product.maxQuantity,10);if(maxQuantity!=null)
{if(newQuantity>maxQuantity)
{if($.isFunction(simpleCart.onRejectAdd))
simpleCart.onRejectAdd(this.name,this.quantity,maxQuantity);return false;}}}catch(err){error(err)}
return true;};CartItem.prototype.parseValuesFromArray=function(array){if(array&&array.length&&array.length>0){for(var x=0,xlen=array.length;x<xlen;x++){array[x].replace(/||/,"| |");array[x].replace(/\+\+/,"+ +");var value=array[x].split('=');if(value.length>1){if(value.length>2){for(var j=2,jlen=value.length;j<jlen;j++){value[1]=value[1]+"="+value[j];}}
var valueToUse=unescape(value[1]);if(valueToUse=="true"||valueToUse=="false")
valueToUse=(unescape(value[1])=="true");var key=unescape(value[0]).toLowerCase();if(key!="product"){this[key]=valueToUse;}
if(key=="product_id"){this.product=simpleCart.products[valueToUse];}}}
return true;}else{return false;}};CartItem.prototype.remove=function(){simpleCart.remove(this.id);if($.isFunction(simpleCart.onItemRemove)){simpleCart.onItemRemove(this);}
simpleCart.update();};CartItem.prototype.getTotal=function(currencyCode){var q=parseInt(this.quantity,10);if(this.udp==undefined||this.udp)
var discount=true;else
var discount=false;if(this.product!=undefined){var p=this.product;var c;var tQ=q;if(currencyCode!==undefined)
c=p.getCurrency(currencyCode);else
c=p.defaultCurrency;if(c.incrementalPricing){var sortedPrices=p.sortPricingByMax(c.pricing);var total=0.0;for(i in sortedPrices){var priceObj=sortedPrices[i];var price=p.getPrice(priceObj.max,discount,currencyCode)
if(priceObj.max<q){total+=price*priceObj.max;tQ-=priceObj.max;}
else{total+=price*tQ;break;}}
return total;}
else
return p.getPrice(q,discount,currencyCode)*q;}
else
return this.price*q;};function Shelf(){this.items={};}
Shelf.prototype.readPage=function(){this.items={};var newItems=getElementsByClassName("simpleCart_shelfItem");for(var current in newItems){var newItem=new ShelfItem();this.checkChildren(newItems[current],newItem);this.items[newItem.id]=newItem;}};Shelf.prototype.checkChildren=function(item,newItem){for(var x=0;item.childNodes[x];x++){var node=item.childNodes[x];if(node.className&&node.className.match(/item_[^ ]+/)){var data=/item_[^ ]+/.exec(node.className)[0].split("_");if(data[1]=="add"||data[1]=="Add"){var tempArray=[];tempArray.push(node);var addFunction=simpleCart.Shelf.addToCart(newItem.id);simpleCart.addEventToArray(tempArray,addFunction,"click");node.id=newItem.id;}else{newItem[data[1]]=node;}}
if(node.childNodes[0]){this.checkChildren(node,newItem);}}};Shelf.prototype.empty=function(){this.items={};};Shelf.prototype.addToCart=function(id){return function(){if(simpleCart.Shelf.items[id]){simpleCart.Shelf.items[id].addToCart();}else{error("Shelf item with id of "+id+" does not exist.");}};};function ShelfItem(){this.id="s"+NextId++;}
ShelfItem.prototype.remove=function(){simpleCart.Shelf.items[this.id]=null;};ShelfItem.prototype.addToCart=function(){var outStrings=[],valueString;for(var field in this){if(typeof(this[field])!="function"&&field!="id"){valueString="";switch(field){case"price":if(this[field].value){valueString=this[field].value;}else if(this[field].innerHTML){valueString=this[field].innerHTML;}
valueString=valueString.replace(/[^(\d|\.)]*/gi,"");valueString=valueString.replace(/,*/,"");break;case"image":valueString=this[field].src;break;default:if(this[field].value){valueString=this[field].value;}else if(this[field].innerHTML){valueString=this[field].innerHTML;}else if(this[field].src){valueString=this[field].src;}else{valueString=this[field];}
break;}
outStrings.push(field+"="+valueString);}}
simpleCart.add(outStrings);};function createCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*1000));var expires="; expires="+date.toGMTString();}
else var expires="";document.cookie=name+"="+value+expires+"; path=/";}
function readCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1,c.length);if(c.indexOf(nameEQ)===0)return c.substring(nameEQ.length,c.length);}
return null;}
function eraseCookie(name){createCookie(name,"",-1);}
var getElementsByClassName=function(className,tag,elm){if(document.getElementsByClassName){getElementsByClassName=function(className,tag,elm){elm=elm||document;var elements=elm.getElementsByClassName(className),nodeName=(tag)?new RegExp("\\b"+tag+"\\b","i"):null,returnElements=[],current;for(var i=0,il=elements.length;i<il;i+=1){current=elements[i];if(!nodeName||nodeName.test(current.nodeName)){returnElements.push(current);}}
return returnElements;};}
else if(document.evaluate){getElementsByClassName=function(className,tag,elm){tag=tag||"*";elm=elm||document;var classes=className.split(" "),classesToCheck="",xhtmlNamespace="http://www.w3.org/1999/xhtml",namespaceResolver=(document.documentElement.namespaceURI===xhtmlNamespace)?xhtmlNamespace:null,returnElements=[],elements,node;for(var j=0,jl=classes.length;j<jl;j+=1){classesToCheck+="[contains(concat(' ', @class, ' '), ' "+classes[j]+" ')]";}
try{elements=document.evaluate(".//"+tag+classesToCheck,elm,namespaceResolver,0,null);}
catch(e){elements=document.evaluate(".//"+tag+classesToCheck,elm,null,0,null);}
while((node=elements.iterateNext())){returnElements.push(node);}
return returnElements;};}
else{getElementsByClassName=function(className,tag,elm){tag=tag||"*";elm=elm||document;var classes=className.split(" "),classesToCheck=[],elements=(tag==="*"&&elm.all)?elm.all:elm.getElementsByTagName(tag),current,returnElements=[],match;for(var k=0,kl=classes.length;k<kl;k+=1){classesToCheck.push(new RegExp("(^|\\s)"+classes[k]+"(\\s|$)"));}
for(var l=0,ll=elements.length;l<ll;l+=1){current=elements[l];match=false;for(var m=0,ml=classesToCheck.length;m<ml;m+=1){match=classesToCheck[m].test(current.className);if(!match){break;}}
if(match){returnElements.push(current);}}
return returnElements;};}
return getElementsByClassName(className,tag,elm);};function ProductInfo(){var self=this;self.id=null;self.name="";self.maxQuantity=0;self.maxDuration=0;self.currencies=[];self.defaultCurrency=null;self.shippingMethods=[];};ProductInfo.prototype.sortPricingByMax=function(prices){var self=this;var sortedPrices=prices;sortedPrices.sort(function(a,b){return(a.max-b.max);});return sortedPrices;};ProductInfo.prototype.getVolumePrice=function(prices,qty){var self=this;sortedPrices=self.sortPricingByMax(prices);for(i in sortedPrices){var price=sortedPrices[i];if(price.max>=qty)
return price;}
return null;};ProductInfo.prototype.getPrice=function(qty,discount,currencyCode){var self=this;var priceObj=null;if(currencyCode!==undefined){var currency=self.getCurrency(currencyCode);priceObj=self.getVolumePrice(currency.pricing,qty);}
else if(self.defaultCurrency!==null){priceObj=self.getVolumePrice(self.defaultCurrency.pricing,qty);}
if(priceObj===null){return null;}
if(discount)
return priceObj.discountPrice;else
return priceObj.price;};ProductInfo.prototype.getCurrency=function(currencyCode){var self=this;for(i in self.currencies){var currency=self.currencies[i];if(currency.code==currencyCode.toUpperCase()){return currency;}}
return null;};ProductInfo.prototype.getHandlingPrice=function(methodId,qty){var self=this;for(i in self.shippingMethods){method=self.shippingMethods[i];if(method.id==methodId){var priceObj=self.getVolumePrice(method.pricing,qty);return priceObj.handling;}}
return null;};ProductInfo.prototype.getShippingPrice=function(methodId,qty){var self=this;for(i in self.shippingMethods){method=self.shippingMethods[i];if(method.id==methodId){var priceObj=self.getVolumePrice(method.pricing,qty);return priceObj.shipping;}}
return null;};ProductInfo.prototype.addCurrency=function(c){var self=this;self.currencies.push(c);};ProductInfo.prototype.setDefaultCurrency=function(currency){var self=this;self.defaultCurrency=currency;};ProductInfo.prototype.hasCurrency=function(currencyCode){var self=this;for(var i in self.currencies){var currency=self.currencies[i];if(currency.code==currencyCode.toUpperCase()){return true;}}
return false;};ProductInfo.prototype.addShippingMethod=function(method){var self=this;self.shippingMethods.push(method);};String.prototype.reverse=function(){return this.split("").reverse().join("");};Number.prototype.withCommas=function(){var x=6,y=parseFloat(this).toFixed(2).toString().reverse();while(x<y.length){y=y.substring(0,x)+","+y.substring(x);x+=4;}return y.reverse();};Number.prototype.toCurrency=function(sign,decimal,after,scale){sign=(sign==undefined?"$":sign);decimal=(decimal==undefined?",":decimal);after=(after==undefined?false:after);scale=(scale==undefined?2:scale)
var num=this.formatMoney(scale,decimal,',');return(after?num+sign:sign+num);};Number.prototype.formatMoney=function(c,d,t){var n=this,c=isNaN(c=Math.abs(c))?2:c,d=d==undefined?",":d,t=t==undefined?".":t,s=n<0?"-":"",i=parseInt(n=Math.abs(+n||0).toFixed(c))+"",j=(j=i.length)>3?j%3:0;return s+(j?i.substr(0,j)+t:"")+i.substr(j).replace(/(\d{3})(?=\d)/g,"$1"+t)+(c?d+Math.abs(n-i).toFixed(c).slice(2):"");};function error(message){try{console.log(message);}catch(err){}}